Add support for Kong 0.10
esatterwhite/node-kingkong pull request #2
Opened 2017-04-04 14:35 UTC by brothhaar

Added support for Kong 0.10. This included changes to api
validation to support backwards incompatible field changes. Also
added a package config `kongVersion`. This is currently defaulted
to `0.9` but can be set by`npm config set kingkong:kongVersion 0.10`
to test against other Kong versions. Tests are configured to use
`kongVersion` as part of the spec file name.

2017-04-05 12:57 UTC, esatterwhite requested changes
I'd rather not try to support every breaking change to kong. We have semver for that. Lets just drop the old 0.9 code and get rid of the npm config stuff

2017-04-05 12:57 UTC, esatterwhite commented on lib/validation/api.js
> +  , uris:               joi.array().items(joi.string().optional())
If `0.9` and `0.10` don't have a compatible API, I don't think this project should try to maintain compatibility with breaking changes in the project.

Someone could Have `0.10` Kong instance running and make a valid `0.9` request. 

I'd much rather follow suite: just make the changes required to work with `0.10`, disregard `0.9`. I'll just publish a new major version.

I can set up CI to run on a tag for each Kong version. Less cruft in the code, less prone to user error and easier to deal with.

Mind just removing the old `0.9` stuff? 

Thanks!

2017-04-10 17:10 UTC, brothhaar commented
@esatterwhite Good call. I removed the 0.9 compatibility.

2017-04-11 21:34 UTC, esatterwhite approved these changes

2017-04-11 21:34 UTC, merged