get method bugfix
esatterwhite/node-kingkong pull request #3
Opened 2017-04-27 11:48 UTC by o100ja

This was probably a copy-paste from the list method that simply was overlooked.

2017-04-29 15:25 UTC, esatterwhite requested changes
Ya, it kind of looks that way. Would you mind adding a simple test for this?

can really just be a create w/ a get & verify the data matches. That would be awesome!

2017-05-23 15:58 UTC, o100ja commented
I've extended the test a bit to cover the change I've added, but I simply can't find the time to do a full CRUD test, especially for each API endpoint. Since I'll be relying on this library on a project I'm working on currently (and relentlessly :sweat:) I'll try to extend the tests a bit more when I accumulate enough time to work on that.

2017-05-23 16:00 UTC, esatterwhite approved these changes

2017-05-23 16:00 UTC, esatterwhite commented on lib/index.js
> +        return resp.body;
we can do away with the variable assignment here too and just
```js
return (yeild this.request('get', resource, id)).body;
```

2017-05-23 16:01 UTC, esatterwhite commented
Thanks! Look forward to anymore additions that may come.

2017-05-23 16:02 UTC, merged

2017-05-23 16:04 UTC, esatterwhite commented
2.0.1 published to npm